add rlpd framework
jlidard/dppo-dev pull request #1
Opened 2024-09-19 23:49 UTC by jlidard

2024-09-21 05:12 UTC, allenzren reviewed
> Reviewed 7 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/jlidard/dppo-dev/1)* status: 7 of 20 files reviewed, 20 unresolved discussions (waiting on @jlidard)

*[a discussion](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7HylNf28trwqZWfr2t:-O7HylNf28trwqZWfr2u:b-sl6dpq) (no related file):*
Are you using Black? the code has a lot of extra newlines

___
___
*[`agent/dataset/sequence.py` line 56 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7Hr-Io3f6hTszLJQKJ:-O7Hr-Io3f6hTszLJQKK:b649p6x) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/dataset/sequence.py#L56)):*
> ```Python
>         # Load dataset to device specified
>         if dataset_path.endswith(".npz"):
>             # Note: why allow_pickle=False? 
> ```

Do you need data type other than np array in npz? otherwise let's keep `allow_pickle` to False; it is a good practice to use clean data type and avoid pickle 
___
*[`agent/dataset/sequence.py` line 128 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7HrNcv9KclFRdUwLQV:-O7HrNcv9KclFRdUwLQW:b-lkl7wl) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/dataset/sequence.py#L128)):*
> ```Python
>         return indices
>     
>     def make_indices(self, traj_lengths, horizon_steps):
> ```

remove this function? somehow this commit adds this function
___
*[`agent/dataset/sequence.py` line 193 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7HrwYc2THKIWRYnXad:-O7HrwYc2THKIWRYnXae:bb69l0f) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/dataset/sequence.py#L193)):*
> ```Python
>         traj_lengths = dataset["traj_lengths"][:max_n_episodes]  # 1-D array
>         total_num_steps = np.sum(traj_lengths)
> ```

extra newline
___
*[`agent/dataset/sequence.py` line 204 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7Hs-VZ2I6aOG2dexhl:-O7Hs-VZ2I6aOG2dexhm:bjse0ba) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/dataset/sequence.py#L204)):*
> ```Python
>         cumulative_traj_length = np.cumsum(traj_lengths)
>         for i, traj_length in enumerate(cumulative_traj_length):
>             self.done[traj_length - 1] = 1 # todo: check this
> ```

all good? it looks fine to me
___
*[`agent/dataset/sequence.py` line 208 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7HsDRB2rg7FVIGUQa4:-O7HsDRB2rg7FVIGUQa5:bvyrx6c) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/dataset/sequence.py#L208)):*
> ```Python
> 
>     def __getitem__(self, idx):
>         # unlike StitchedSequenceDataset, we only sample a single transition
> ```

This comment is a bit confusing --- we are still sampling multiple transitions if we set `horizon_steps>1`. We can remove this comment
___
*[`agent/finetune/train_rlpd_agent.py` line 2 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7HxZhy4oJMFaLuIJSy:-O7HxZhy4oJMFaLuIJSz:be04nof) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/finetune/train_rlpd_agent.py#L2)):*
> ```Python
> """
> Diffusion Q-Learning (DQL)
> ```

update header
___
*[`agent/finetune/train_rlpd_agent.py` line 34 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7HxgFo-i1wT9Mx0ebx:-O7HxgFo-i1wT9Mx0eby:b-og2gak) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/finetune/train_rlpd_agent.py#L34)):*
> ```Python
> 
>         # Build dataset
>         self.dataset_train = hydra.utils.instantiate(cfg.train_dataset)
> ```

let's maybe use `cfg.offline_dataset`? `train` is ambiguous in offline vs. online.
Also then let's call it self.dataset_offline
___
*[`agent/finetune/train_rlpd_agent.py` line 35 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7HxsryCnIeq8_J_2K_:-O7HxsryCnIeq8_J_2Ka:b-cnu8y) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/finetune/train_rlpd_agent.py#L35)):*
> ```Python
>         # Build dataset
>         self.dataset_train = hydra.utils.instantiate(cfg.train_dataset)
>         self.dataloader_train = torch.utils.data.DataLoader(
> ```

self.dataloader_offline
___
*[`agent/finetune/train_rlpd_agent.py` line 89 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7HyUoI6emQ_b1k0GHR:-O7HyUoI6emQ_b1k0GHS:bm4q4d) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/finetune/train_rlpd_agent.py#L89)):*
> ```Python
> 
>         # Number of batches per learning update
>         self.num_batch = cfg.train.num_batch
> ```

could we use something more meaningful like `replay_ratio` instead? We can calculate number of batches based on replay_ratio and number of experiences collected per update
___
*[`agent/finetune/train_rlpd_agent.py` line 234 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7Hyfn-29V3A7fQA-hE:-O7Hyfn00kCDR3YsvK79:bb69l0f) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/finetune/train_rlpd_agent.py#L234)):*
> ```Python
>                     rewards_b_off = batch_offline.rewards * self.scale_reward_factor
>                     dones_b_off = batch_offline.dones
> ```

extra newline
___
*[`agent/finetune/train_rlpd_agent.py` line 274 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7HzL0q30xsm9lfjiyv:-O7HzL0q30xsm9lfjiyw:b-6saqb1) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/finetune/train_rlpd_agent.py#L274)):*
> ```Python
>                     rewards_b = torch.cat([rewards_b_off, rewards_b_on], dim=0)
>                     dones_b = torch.cat([dones_b_off, dones_b_on], dim=0)
>                     # obs_b = obs_b_on
> ```

remove these?
___
*[`agent/finetune/train_rlpd_agent.py` line 279 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7HzM7D-zXwBVqJ7i6w:-O7HzM7D-zXwBVqJ7i6x:b-8rb6fg) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/finetune/train_rlpd_agent.py#L279)):*
> ```Python
>                     # rewards_b = rewards_b_on
>                     # dones_b = dones_b_on
> ```

extra newlines
___
*[`cfg/gym/finetune/halfcheetah-v2/ft_rlpd_mlp.yaml` line 74 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7Hv79qEks0lhcqUQNF:-O7Hv79qEks0lhcqUQNG:b-8rb6fg) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/cfg/gym/finetune/halfcheetah-v2/ft_rlpd_mlp.yaml#L74)):*
> ```YAML
>   buffer_size: 1000000
> ```

extra newlines
___
*[`model/rl/gaussian_rlpd.py` line 31 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7HvwRLA9x_fh31YIQZ:-O7HvwRLA9x_fh31YIQ_:b-js1yb4) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/model/rl/gaussian_rlpd.py#L31)):*
> ```Python
> 
>         # initialize critic networks
>         self.critic_networks = []
> ```

self.critic_networks = [deepcopy(critic).to(self.device) for _ in range(n_critic)]
___
*[`model/rl/gaussian_rlpd.py` line 39 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7Hw3D2-YPrQKeo6de8:-O7Hw3D2-YPrQKeo6de9:b-2guby3) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/model/rl/gaussian_rlpd.py#L39)):*
> ```Python
> 
>         # initialize target networks
>         self.target_networks = []
> ```

same here
___
*[`model/rl/gaussian_rlpd.py` line 51 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7Hw7qM96yIztxvFE8_:-O7Hw7qM96yIztxvFE8a:beytdax) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/model/rl/gaussian_rlpd.py#L51)):*
> ```Python
>             param.requires_grad = False
> 
>         self.n_critics = n_critics
> ```

let's put the parameters a [...]

2024-09-21 06:07 UTC, allenzren reviewed
> *[Reviewable](https://reviewable.io/reviews/jlidard/dppo-dev/1)* status: 7 of 20 files reviewed, 27 unresolved discussions (waiting on @jlidard)

___
*[`agent/dataset/sequence.py` line 208 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7HsDRB2rg7FVIGUQa4:-O7I4pHk6tD9Af76dobP:b-nqiz7e) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/dataset/sequence.py#L208)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

This comment is a bit confusing --- we are still sampling multiple transitions if we set `horizon_steps>1`. We can remove this comment
</blockquote></details>

actually I meant we never sample multiple transitions (we can think of action chunk as the current transition)
___
*[`agent/dataset/sequence.py` line 210 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7I53BqDMXewsM6QWPk:-O7I53BqDMXewsM6QWPl:b3yie1) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/dataset/sequence.py#L210)):*
> ```Python
>         # unlike StitchedSequenceDataset, we only sample a single transition
>         start, num_before_start = self.indices[idx]
>         end = start + 1
> ```

let's keep end = start + self.horizon_steps
___
*[`agent/dataset/sequence.py` line 211 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7I4fl47bvhzT96Fq3x:-O7I4fl47bvhzT96Fq3y:b-lqt79s) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/dataset/sequence.py#L211)):*
> ```Python
>         start, num_before_start = self.indices[idx]
>         end = start + 1
>         states = self.states[(start - num_before_start) : end]
> ```

We can instead set states=self.states[(start - num_before_start) : start], also for the other class
___
*[`agent/dataset/sequence.py` line 213 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7I56pX4x2HTusYTn0Z:-O7I4xyBB4cpV2-7BOt2:bvc6n24) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/dataset/sequence.py#L213)):*
> ```Python
>         states = self.states[(start - num_before_start) : end]
>         actions = self.actions[start:end]
>         rewards = self.reward[start:end]
> ```

but only extract one reward / dones instead of using end
___
*[`model/rl/gaussian_rlpd.py` line 72 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7I6H7c8GfG2sDrqdSM:-O7I6H7dB_jFRfobRduv:bmzeu2x) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/model/rl/gaussian_rlpd.py#L72)):*
> ```Python
> 
>         with torch.no_grad():
>             target_q1 = self.target_networks[0] #self.target_networks[q1_ind]
> ```

why 0 and 1? we always only use two target critics?
___
*[`model/rl/gaussian_rlpd.py` line 85 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7I6VHjCjCHbfmz4s7U:-O7I6VHjCjCHbfmz4s7V:blg1cy5) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/model/rl/gaussian_rlpd.py#L85)):*
> ```Python
>                 actions=next_actions,
>             )  # needed for entropy 
>             next_q1 = target_q1(next_obs, next_actions)[0]
> ```

what is [0] for?
___
*[`model/rl/gaussian_rlpd.py` line 125 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7I7JM6DsqiiM27wJqI:-O7I7JM6DsqiiM27wJqJ:b-eyt5ow) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/model/rl/gaussian_rlpd.py#L125)):*
> ```Python
>             current_q.append(current_q_i)
>         current_q = torch.stack(current_q, dim=-1) # (B, n_critics)
>         current_q = torch.min(current_q, dim=-1).values
> ```

I thought the algorithm block (L23) in the paper shows using the mean, not the min?
https://github.com/ikostrikov/rlpd/blob/c90fd4baf28c9c9ef40a81460a2e395092844f88/rlpd/agents/sac/sac_learner.py#L169
___
*[`util/network.py` line 3 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7IAm9m98ehPxQ59nFe:-O7IAm9m98ehPxQ59nFf:bg9uhn8) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/util/network.py#L3)):*
> ```Python
> import torch
> 
> def soft_update(target, source, tau):
> ```

Can you double check this works for a list of critics? like print out the parameters()


<!-- Sent from Reviewable.io -->

2024-09-21 06:16 UTC, allenzren reviewed
> *[Reviewable](https://reviewable.io/reviews/jlidard/dppo-dev/1)* status: 7 of 20 files reviewed, 27 unresolved discussions (waiting on @jlidard)

___
*[`model/rl/gaussian_rlpd.py` line 125 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7IDNvGANCs6pTVsZlM:-O7IDNvGANCs6pTVsZlN:bhgz4fu) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/model/rl/gaussian_rlpd.py#L125)):*
> ```Python
>             current_q.append(current_q_i)
>         current_q = torch.stack(current_q, dim=-1) # (B, n_critics)
>         current_q = torch.min(current_q, dim=-1).values
> ```

what is .values for


<!-- Sent from Reviewable.io -->

2024-09-21 06:26 UTC, allenzren reviewed
> *[Reviewable](https://reviewable.io/reviews/jlidard/dppo-dev/1)* status: 7 of 20 files reviewed, 26 unresolved discussions (waiting on @jlidard)

___
*[`agent/dataset/sequence.py` line 208 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7IFaBNAQvoSXzNFA22:-O7IFaBNAQvoSXzNFA23:b-1cesg6) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/dataset/sequence.py#L208)):*
> ```Python
> 
>     def __getitem__(self, idx):
>         # unlike StitchedSequenceDataset, we only sample a single transition
> ```

We don't need this comment since we always sample only one transition? i don't consider action chunk as multiple transitions (we can treat it as the current action)


<!-- Sent from Reviewable.io -->

2024-09-21 17:19 UTC, allenzren reviewed
> *[Reviewable](https://reviewable.io/reviews/jlidard/dppo-dev/1)* status: 7 of 20 files reviewed, 27 unresolved discussions (waiting on @jlidard)

___
*[`agent/dataset/sequence.py` line 211 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7K_gPzDETfYdO6zXUu:-O7K_gPzDETfYdO6zXUv:b-e01ex2) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/dataset/sequence.py#L211)):*
> ```Python
>         start, num_before_start = self.indices[idx]
>         end = start + 1
>         states = self.states[(start - num_before_start) : end]
> ```

We can instead set states=self.states\[(start - num\_before\_start) : start+1\], also for the other class
___
*[`script/dataset/process_robomimic_dataset.py` line 309 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7K_ruX81GhdPFilcLO:-O7K_ruX81GhdPFilcLP:b7echbs) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/script/dataset/process_robomimic_dataset.py#L309)):*
> ```Python
>     num_out_val = len(out_val["traj_lengths"])
>     for key in new_keys:
>         out_train[key] = np.concatenate([out_train[key][i, :out_train["traj_lengths"][i]] for i in range(num_out_train)], 0)
> ```

if you can, let's clean up the processing script and don't use padding when we loop over the trajectories and directly concatenate the trajectories


<!-- Sent from Reviewable.io -->

2024-09-21 23:44 UTC, jlidard reviewed
> *[Reviewable](https://reviewable.io/reviews/jlidard/dppo-dev/1)* status: 3 of 20 files reviewed, 27 unresolved discussions (waiting on @allenzren)

*[a discussion](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7HylNf28trwqZWfr2t:-O7LnGhD2tbI669T_tdh:bosivpn) (no related file):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

Are you using Black? the code has a lot of extra newlines
</blockquote></details>

Ah I didn't have it running on the new repo. I added a pre-commit hook so it should run automatically now. 

___
___
*[`agent/dataset/sequence.py` line 56 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7Hr-Io3f6hTszLJQKJ:-O7LhiCu4NdY68wDYE8q:b-896fix) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/dataset/sequence.py#L56)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

Do you need data type other than np array in npz? otherwise let's keep `allow_pickle` to False; it is a good practice to use clean data type and avoid pickle
</blockquote></details>

Done.
___
*[`agent/dataset/sequence.py` line 128 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7HrNcv9KclFRdUwLQV:-O7LhgpbCpqExk8HMZp3:b-896fix) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/dataset/sequence.py#L128)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

remove this function? somehow this commit adds this function
</blockquote></details>

Done.
___
*[`agent/dataset/sequence.py` line 193 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7HrwYc2THKIWRYnXad:-O7Ln4RY8q8XBBZ8Dxnt:b-896fix) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/dataset/sequence.py#L193)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

extra newline
</blockquote></details>

Done.
___
*[`agent/dataset/sequence.py` line 204 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7Hs-VZ2I6aOG2dexhl:-O7Ln4mX5l9mpGcVVQfk:b-896fix) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/dataset/sequence.py#L204)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

all good? it looks fine to me
</blockquote></details>

Done.
___
*[`agent/dataset/sequence.py` line 208 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7HsDRB2rg7FVIGUQa4:-O7Ljns5EzFhQxn02xtS:bll5iww) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/dataset/sequence.py#L208)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

actually I meant we never sample multiple transitions (we can think of action chunk as the current transition)
</blockquote></details>

I changed it to emphasize that we're sampling reward and done as well. I think that's the only change from the other dataset. 
___
*[`agent/dataset/sequence.py` line 208 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7IFaBNAQvoSXzNFA22:-O7Ljn1UEbdlX0YZRTFT:b-896fix) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/dataset/sequence.py#L208)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

We don't need this comment since we always sample only one transition? i don't consider action chunk as multiple transitions (we can treat it as the current action)
</blockquote></details>

Done.
___
*[`agent/dataset/sequence.py` line 210 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7I53BqDMXewsM6QWPk:-O7LjvKw4MFhvhl0fZ-w:b-koxtq1) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/dataset/sequence.py#L210)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

let's keep end = start + self.horizon_steps
</blockquote></details>

Done. I had to modify the next states logic a bit to prevent indexing overruns when we have self.horizon_steps > 1. 
___
*[`agent/dataset/sequence.py` line 211 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7K_gPzDETfYdO6zXUu:-O7LjXf_DuT6nv-kju_z:b-896fix) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/dataset/sequence.py#L211)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

We can instead set states=self.states\[(start - num\_before\_start) : start+1\], also for the other class
</blockquote></details>

Done.
___
*[`agent/dataset/sequence.py` line 213 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7I56pX4x2HTusYTn0Z:-O7Lj_GXB2nM-nLCjxx-:b-896fix) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/dataset/sequence.py#L213)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

but only extract one reward / dones instead of using end
</blockquote></details>

Done.
___
*[`agent/finetune/train_rlpd_agent.py` line 2 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7HxZhy4oJMFaLuIJSy:-O7LkNH16uuI0RQmFwxq:b-896fix) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/finetune/train_rlpd_agent.py#L2)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

update header
</blockquote></details>

Done.
___
*[`agent/finetune/train_rlpd_agent.py` line 34 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7HxgFo-i1wT9Mx0ebx:-O7LlJcPE8VQ8yk9dKqs:b-896fix) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/finetune/train_rlpd_agent.py#L34)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

let's maybe use `cfg.offline_dataset`? `train` is ambiguous in offline vs. online.
Also then let's call it self.dataset_offline
</blockquote></details>

Done.
___
*[`agent/finetune/train_rlpd_agent.py` line 35 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7HxsryCnIeq8_J_2K_:-O7LlLGiCKyYY4IZeYck:b-896fix) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/finetune/train_rlpd_agent.py#L35)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

self.dataloader_offline
</blockquote></details>

Done.
___
*[`agent/finetune/train_rlpd_agent.py` line 89 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7HyUoI6emQ_b1k0GHR:-O7LlcK3CD_1p--MDa6n:b-896fix) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/finetune/train_rlpd_agent.py#L89)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

could we use something more meaningful like `replay_ratio` instead? We can calculate number of batches based on replay_ratio and number of experiences collected per update
</blockquote></details>

Done.
___
*[`agent/finetune/train_rlpd_agent.py` line 234 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7Hyfn-29V3A7fQA-hE:-O7LlwDDBHOr1O2kuYzB:b-896fix) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/finetune/train_rlpd_agent.py#L234)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

extra newline
</blockquote></details>

Done.
___
*[`agent/finetune/train_rlpd_agent.py` line 274 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7HzL0q30xsm9lfjiyv:-O7LlzHp0ROyrZL1axEH:b-896fix) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/agent/finetune/train_rlpd_agent.py#L274)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary>< [...]

2024-09-22 00:19 UTC, allenzren reviewed
> Reviewed 19 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/jlidard/dppo-dev/1)* status: all files reviewed, 4 unresolved discussions (waiting on @jlidard)

___
*[`agent/dataset/sequence.py` line 198 at r2](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7M3Z6H-GFEPPB_-BHV:-O7M3Z6H-GFEPPB_-BHW:b-ib1l2e) ([raw file](https://github.com/jlidard/dppo-dev/blob/6595519d73211f8961c894f56d4e2afeb8088bd8/agent/dataset/sequence.py#L198)):*
> ```Python
>         rewards = self.reward[start:end][-1:]
>         dones = self.done[start:end][-1:]
>         if idx < len(self.indices) - self.horizon_steps:
> ```

Do we need this? I am thinking we should still use any idx before the last one. We don't need self.horizon_steps in the indexing of `next_states`?
___
*[`agent/dataset/sequence.py` line 200 at r2](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7M4Ela-wEzn5e3GFJY:-O7M4Ela-wEzn5e3GFJZ:b-w6q2dt) ([raw file](https://github.com/jlidard/dppo-dev/blob/6595519d73211f8961c894f56d4e2afeb8088bd8/agent/dataset/sequence.py#L200)):*
> ```Python
>         if idx < len(self.indices) - self.horizon_steps:
>             next_states = self.states[
>                 (start - num_before_start) : start + self.horizon_steps
> ```

Shouldn't this be [(start - num_before_start + 1) : (start + 1 + 1)]?
___
*[`agent/finetune/train_rlpd_agent.py` line 121 at r2](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7M4LJW83A5AsfK5Fl5:-O7M4LJW83A5AsfK5Fl6:b-90gwi9) ([raw file](https://github.com/jlidard/dppo-dev/blob/6595519d73211f8961c894f56d4e2afeb8088bd8/agent/finetune/train_rlpd_agent.py#L121)):*
> ```Python
>                 firsts_trajs[0] = 1
>             else:
>                 firsts_trajs[
> ```

weird formatting, is this from black? otherwise let's revert the change
___
*[`cfg/gym/finetune/halfcheetah-v2/ft_rlpd_mlp.yaml` line 71 at r2](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7M4Run0g6oD1VDCIqt:-O7M4Run0g6oD1VDCIqu:b-gefoju) ([raw file](https://github.com/jlidard/dppo-dev/blob/6595519d73211f8961c894f56d4e2afeb8088bd8/cfg/gym/finetune/halfcheetah-v2/ft_rlpd_mlp.yaml#L71)):*
> ```YAML
>   target_ema_rate: 0.005         # rho in RLPD paper
>   scale_reward_factor: 1.0    # multiply reward by this amount for more stable value estimation
>   replay_ratio: 64           # number of batches to sample for each learning update
> ```

Is 64 consistent with the experiments from the RLPD paper?
___
*[`util/network.py` line 3 at r1](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7IAm9m98ehPxQ59nFe:-O7M55LR1nFfET25JOZJ:bwtmads) ([raw file](https://github.com/jlidard/dppo-dev/blob/35f0578d73ba40cc47d4790b900ab2383d7b44ec/util/network.py#L3)):*
<details><summary><i>Previously, jlidard (Justin Lidard) wrote…</i></summary><blockquote>

Yeah I checked, it looks like this still works for nn.ParameterList(). Note that only two of the targets should have this update since we only update two of the critics. The critic networks that don't get sampled shouldn't have any update, so the target networks will remain the same as well.
</blockquote></details>

Okay thanks


<!-- Sent from Reviewable.io -->

2024-09-22 04:42 UTC, allenzren reviewed
> Reviewed 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/jlidard/dppo-dev/1)* status: all files reviewed, 2 unresolved discussions (waiting on @jlidard)

___
*[`agent/finetune/train_rlpd_agent.py` line 145 at r4](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7N1DVkAM9h7OTJckDC:-O7N1DVkAM9h7OTJckDD:bd3ektz) ([raw file](https://github.com/jlidard/dppo-dev/blob/37fdc13c865271fbb265018e277682dd0ea0fd56/agent/finetune/train_rlpd_agent.py#L145)):*
> ```Python
> 
>                 # Select action
>                 with torch.no_grad():
> ```

maybe an option for sampling random actions at the beginning of training


<!-- Sent from Reviewable.io -->

2024-09-22 05:11 UTC, jlidard reviewed
> *[Reviewable](https://reviewable.io/reviews/jlidard/dppo-dev/1)* status: 18 of 20 files reviewed, 2 unresolved discussions (waiting on @allenzren)

___
*[`agent/dataset/sequence.py` line 198 at r2](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7M3Z6H-GFEPPB_-BHV:-O7N-JAOBzD9n10mQMEE:bw0g7r9) ([raw file](https://github.com/jlidard/dppo-dev/blob/6595519d73211f8961c894f56d4e2afeb8088bd8/agent/dataset/sequence.py#L198)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

Do we need this? I am thinking we should still use any idx before the last one. We don't need self.horizon_steps in the indexing of `next_states`?
</blockquote></details>

Yeah I think we can use any number of conditioning steps before start as long as start is before the last index. So I will replace it with idx < len(self.indices) - 1 
___
*[`agent/dataset/sequence.py` line 200 at r2](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7M4Ela-wEzn5e3GFJY:-O7MzlFN2bp6FAxm3WT-:b-txuxv6) ([raw file](https://github.com/jlidard/dppo-dev/blob/6595519d73211f8961c894f56d4e2afeb8088bd8/agent/dataset/sequence.py#L200)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

Shouldn't this be [(start - num_before_start + 1) : (start + 1 + 1)]?
</blockquote></details>

Yeah, I think that's correct
___
*[`agent/finetune/train_rlpd_agent.py` line 121 at r2](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7M4LJW83A5AsfK5Fl5:-O7MhOBxB4yjzn2-ZQ0M:b-npi3gk) ([raw file](https://github.com/jlidard/dppo-dev/blob/6595519d73211f8961c894f56d4e2afeb8088bd8/agent/finetune/train_rlpd_agent.py#L121)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

weird formatting, is this from black? otherwise let's revert the change
</blockquote></details>

Yes it's black, sometimes it does that if there's a trailing comment
___
*[`agent/finetune/train_rlpd_agent.py` line 145 at r4](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7N1DVkAM9h7OTJckDC:-O7N84qp0hJwF1125SUm:b-896fix) ([raw file](https://github.com/jlidard/dppo-dev/blob/37fdc13c865271fbb265018e277682dd0ea0fd56/agent/finetune/train_rlpd_agent.py#L145)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

maybe an option for sampling random actions at the beginning of training
</blockquote></details>

Done.
___
*[`cfg/gym/finetune/halfcheetah-v2/ft_rlpd_mlp.yaml` line 71 at r2](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7M4Run0g6oD1VDCIqt:-O7Mz1Pa3cMsRfBNg5pQ:bvobwvk) ([raw file](https://github.com/jlidard/dppo-dev/blob/6595519d73211f8961c894f56d4e2afeb8088bd8/cfg/gym/finetune/halfcheetah-v2/ft_rlpd_mlp.yaml#L71)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

Is 64 consistent with the experiments from the RLPD paper?
</blockquote></details>

Added a few more params to make the critic update occur more frequently than the actor (UTD_ratio=20 in the paper)


<!-- Sent from Reviewable.io -->

2024-09-22 05:16 UTC, allenzren reviewed
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/jlidard/dppo-dev/1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jlidard)



<!-- Sent from Reviewable.io -->

2024-09-22 06:45 UTC, allenzren reviewed
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/jlidard/dppo-dev/1)* status: all files reviewed, 1 unresolved discussion (waiting on @jlidard)

___
*[`agent/finetune/train_rlpd_agent.py` line 142 at r6](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7NT_So8hE8moaNr6t0:-O7NT_So8hE8moaNr6t1:b-798iik) ([raw file](https://github.com/jlidard/dppo-dev/blob/407ec7d53fe3b2e7f9495aac257dc91fa4cfde65/agent/finetune/train_rlpd_agent.py#L142)):*
> ```Python
>                 prev_obs_venv = self.reset_env_all(options_venv=options_venv)
>                 firsts_trajs[0] = 1
>                 env_step = 0
> ```

it doesn't seem that we need `env_step`?


<!-- Sent from Reviewable.io -->

2024-09-22 14:56 UTC, jlidard reviewed
> *[Reviewable](https://reviewable.io/reviews/jlidard/dppo-dev/1)* status: 18 of 20 files reviewed, 1 unresolved discussion (waiting on @allenzren)

___
*[`agent/finetune/train_rlpd_agent.py` line 142 at r6](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7NT_So8hE8moaNr6t0:-O7PDzCQ-oGPwAj0rHrG:b-896fix) ([raw file](https://github.com/jlidard/dppo-dev/blob/407ec7d53fe3b2e7f9495aac257dc91fa4cfde65/agent/finetune/train_rlpd_agent.py#L142)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

it doesn't seem that we need `env_step`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-22 15:09 UTC, jlidard reviewed
> *[Reviewable](https://reviewable.io/reviews/jlidard/dppo-dev/1)* status: 18 of 20 files reviewed, 1 unresolved discussion (waiting on @allenzren)

___
*[`agent/dataset/sequence.py` line 200 at r2](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7M4Ela-wEzn5e3GFJY:-O7PG_iCAJCpvQ4MfSrg:bxhhqdt) ([raw file](https://github.com/jlidard/dppo-dev/blob/6595519d73211f8961c894f56d4e2afeb8088bd8/agent/dataset/sequence.py#L200)):*
<details><summary><i>Previously, jlidard (Justin Lidard) wrote…</i></summary><blockquote>

Yeah, I think that's correct
</blockquote></details>

wait actually what happens when self.horizon_steps is greater than 1? Wouldn't it be [(start - num_before_start + self.horizon_steps) : (start + 1 + self.horizon_steps)] ?


<!-- Sent from Reviewable.io -->

2024-09-22 17:37 UTC, allenzren reviewed
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/jlidard/dppo-dev/1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jlidard)

___
*[`agent/dataset/sequence.py` line 200 at r2](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7M4Ela-wEzn5e3GFJY:-O7PnbDE7taVn_lhEQ8a:b8etbix) ([raw file](https://github.com/jlidard/dppo-dev/blob/6595519d73211f8961c894f56d4e2afeb8088bd8/agent/dataset/sequence.py#L200)):*
<details><summary><i>Previously, jlidard (Justin Lidard) wrote…</i></summary><blockquote>

wait actually what happens when self.horizon_steps is greater than 1? Wouldn't it be [(start - num_before_start + self.horizon_steps) : (start + 1 + self.horizon_steps)] ?
</blockquote></details>

we don't need horizon_steps for next_states or states? it is only relevant for actions. It is basically the action chunk size


<!-- Sent from Reviewable.io -->

2024-09-24 15:28 UTC, allenzren requested changes
> Reviewed 4 of 6 files at r9, 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/jlidard/dppo-dev/1)* status: all files reviewed, 3 unresolved discussions (waiting on @jlidard)

___
*[`agent/dataset/sequence.py` line 198 at r10](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7ZcN2V2rDS_pp9bSU9:-O7ZcN2V2rDS_pp9bSUA:b-hfpv1m) ([raw file](https://github.com/jlidard/dppo-dev/blob/a23987410b248bc8e5d9653f4697b94ecb2d7e98/agent/dataset/sequence.py#L198)):*
> ```Python
>         # Compute the difference between states by rolling and taking the norm
>         # in the last dimension. We set any transition with difference above the threshold to done.
>         if use_obs_diff_done:
> ```

remove?
___
*[`agent/finetune/train_sac_agent.py` line 216 at r10](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7ZcqNwEvpcBI-2u95R:-O7ZcqNwEvpcBI-2u95S:b-vr87dy) ([raw file](https://github.com/jlidard/dppo-dev/blob/a23987410b248bc8e5d9653f4697b94ecb2d7e98/agent/finetune/train_sac_agent.py#L216)):*
> ```Python
> 
>                 for _ in range(num_batch):
>                     inds = np.random.choice(len(obs_buffer), self.batch_size // 2)
> ```

use full batch size
___
*[`cfg/gym/finetune/hopper-v2/ft_sac_mlp.yaml` line 69 at r10](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7Zd7ELBZmTML256aeG:-O7Zd7ELBZmTML256aeH:b-ao4jjf) ([raw file](https://github.com/jlidard/dppo-dev/blob/a23987410b248bc8e5d9653f4697b94ecb2d7e98/cfg/gym/finetune/hopper-v2/ft_sac_mlp.yaml#L69)):*
> ```YAML
>   target_ema_rate: 0.005         # rho in SAC paper
>   scale_reward_factor: 1.0      # multiply reward by this amount for more stable value estimation
>   replay_ratio: 20               # number of batches to sample for each learning update
> ```

this is very very high. Right now the actual replay ratio is actually this number times the batch size. Usually in SAC we use 4-32 for replay raito.


<!-- Sent from Reviewable.io -->

2024-09-24 16:03 UTC, jlidard reviewed
> *[Reviewable](https://reviewable.io/reviews/jlidard/dppo-dev/1)* status: 22 of 26 files reviewed, 3 unresolved discussions (waiting on @allenzren)

___
*[`agent/dataset/sequence.py` line 200 at r2](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7M4Ela-wEzn5e3GFJY:-O7ZlI2F5YzpJ2MPhwvZ:b-y4011i) ([raw file](https://github.com/jlidard/dppo-dev/blob/6595519d73211f8961c894f56d4e2afeb8088bd8/agent/dataset/sequence.py#L200)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

we don't need horizon_steps for next_states or states? it is only relevant for actions. It is basically the action chunk size
</blockquote></details>

Changed back based on our discussion. 
___
*[`agent/dataset/sequence.py` line 198 at r10](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7ZcN2V2rDS_pp9bSU9:-O7ZlFAW-cnxSdwRiHzy:b-896fix) ([raw file](https://github.com/jlidard/dppo-dev/blob/a23987410b248bc8e5d9653f4697b94ecb2d7e98/agent/dataset/sequence.py#L198)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

remove?
</blockquote></details>

Done.
___
*[`agent/finetune/train_sac_agent.py` line 216 at r10](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7ZcqNwEvpcBI-2u95R:-O7ZlLYD-PXMf-AL-u19:b-896fix) ([raw file](https://github.com/jlidard/dppo-dev/blob/a23987410b248bc8e5d9653f4697b94ecb2d7e98/agent/finetune/train_sac_agent.py#L216)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

use full batch size
</blockquote></details>

Done.
___
*[`cfg/gym/finetune/hopper-v2/ft_sac_mlp.yaml` line 69 at r10](https://reviewable.io/reviews/jlidard/dppo-dev/1#-O7Zd7ELBZmTML256aeG:-O7ZlM6U4a6BWna_v_b_:b-896fix) ([raw file](https://github.com/jlidard/dppo-dev/blob/a23987410b248bc8e5d9653f4697b94ecb2d7e98/cfg/gym/finetune/hopper-v2/ft_sac_mlp.yaml#L69)):*
<details><summary><i>Previously, allenzren (Allen Z. Ren) wrote…</i></summary><blockquote>

this is very very high. Right now the actual replay ratio is actually this number times the batch size. Usually in SAC we use 4-32 for replay raito.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-26 13:43 UTC, allenzren approved these changes
> Reviewed 4 of 11 files at r11, 10 of 10 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/jlidard/dppo-dev/1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jlidard)



<!-- Sent from Reviewable.io -->

2024-09-26 13:45 UTC, merged